### ISSUE TITLE
No notification sound even though notify set to true

### ISSUE THREAD

**Issue by thewinterwind** [hannesvdvreken/hipchat#1]
Hi there, great work here!

I using Laravel 4.1 and everything is working fine except there is no sound played when the message is sent. I published the config package and set to true and everything is overriding the package defaults just fine and the message is being sent, just no sound :(  I went in the vendor folder and changed that notify to true as well just to make sure it wasn't using that but still no sound.

My hipchat account preferences should be fine because I also get notifications from Bugsnap (which uses v1 I believe) and I get the sound on those notifications with no problem.

Cheers.

**Comment by MasterGalvin** [comment]
I can't get any notification sound to play with the native Linux HipChat client on Kubuntu 14.04 and Kubuntu 14.10.  How can I help you help me get this issue resolved?

**Comment by hannesvdvreken** [comment]
Try the web app from hipchat itself. If the notification sound works there, there is nothing I can do to help you. Sorry, and good luck!

**Comment by MasterGalvin** [comment]
I'm using the web app merely because of this sound issue, but the native client would be better if it could work... Thanks!

**Comment by hannesvdvreken** [comment]
Sorry, can't help you with that.
