### ISSUE TITLE
Fatal error in dev-master release

### ISSUE THREAD

**Issue by Spadbob** [hannesvdvreken/hipchat#4]
An iterator cannot be used with foreach by reference

1. Symfony\Component\Debug\Exception\FatalErrorException
…/­vendor/­hannesvdvreken/­hipchat/­src/­Notifier.php218

**Comment by k1ng440** [comment]
can you release another version with latest v3.9.2 or better please?

**Comment by hannesvdvreken** [comment]
@k1ng440 v3.9.2 of what?

**Comment by hannesvdvreken** [comment]
Gonna close this issue. One simply should not use dev-master.
