### ISSUE TITLE
question?

### ISSUE THREAD

**Issue by appkr** [hannesvdvreken/hipchat#6]
Skimming through the readme... 
If the `guzzle` client is always required, why didn't you initialize it inside the package like:

``` php
class Notifier implements NotifierInterface
{
    protected $client;

    public function __construct(array $config = [], $rooms = [])
    {
        $this->client = new \Guzzle\Http\Client;
        //...
    }
//...
}
```

Any reason? Other than that, I like your API much!!!

**Comment by hannesvdvreken** [comment]
Hi,

The main reason why this is done is because of testability. When you inject the Client, you can replace that with a "Mock" to check wether the right methods are called on it or not.

Thanks for the kind words!

**Comment by appkr** [comment]
Oh! I see. I heard that guzzle is heavy. But my thought was that by sacrificing the testability, the client can avoid writing one line less(one more for use statement) and could maintain simpler code. Anyway now I understand and respect your philosophy.
